# Trained with A40 (48 GB) x 1 GPUs.
encoder: conmamba
encoder_conf:
  output_size: 256
  num_blocks: 11
  dropout_rate: 0.1
  positional_dropout_rate: 0.05
  input_layer: conv2d
  normalize_before: true
  rel_pos_type: latest
  pos_enc_layer_type: rel_pos
  activation_type: swish
  mamba_d_state: 16
  mamba_d_conv: 4
  mamba_expand: 2
  linear_units: 1024
  cnn_module_kernel: 31

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
num_workers: 4
batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 100
patience: 4
init: none
early_stopping_criterion:
- valid
- cer_ctc
- min
best_model_criterion:
-   - valid
    - cer_ctc
    - min
keep_nbest_models: 5
use_amp: true

optim: adamw
optim_conf:
    lr: 0.002
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 1.0e-06
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 8000

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5
